version: "3.7"
services:
  app:
    build: ./
    command: yarn ts-node src/app.ts
    restart: always
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - "mariadb"

  app-cron:
    build: ./
    command: yarn ts-node src/cron.ts
    restart: always
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - "mariadb"

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "thepasswordyouwanttoaccessthedatabase"
      MARIADB_DATABASE: "spydog"
      MARIADB_USER: "spydog"
      MARIADB_PASSWORD: "itspasswordforspydog"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - "mariadb"
